### ISSUE TITLE
Does not handle unexpected input 

### ISSUE THREAD

**Issue by anton-ilic** [OlwenL/Personal-Calculator#1]
Checks for unexpected input result do not currently work.

**Comment by SchoIar** [comment]
`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAXINPUT 100
// This calculator will determine the price of a object after applying the newly introduced Luxury Tax


double LuxuryTax (const double PriceOfObject){


  double result; 
  double FinalPrice;
  double PriceA;
  double PriceB;
  

  if(PriceOfObject > 100000){
    
    PriceA = PriceOfObject * 0.10;
    PriceB = (PriceOfObject - 100000)* 0.20;    
    
    if (PriceA < PriceB){
      result = PriceA;
      printf("Method of using total taxable amount by 10%% has been applied\n");
      
    } else if (PriceA > PriceB){  
      result = PriceB;
      printf("Method of multiplying the difference of 100,000 by 20%% has been applied\n");
    }
  
    FinalPrice = result + PriceOfObject;

    printf("\nThe price of the taxes will come out to be $%1.2f, and the total purchase price will be $%1.2f\n", result, FinalPrice );
    
    } else if (PriceOfObject == 0) {
    
      printf("Thank you for using this Calculator!"); 
    
    } else if (PriceOfObject < 100000) {
      printf("Luxury Tax does not apply to items under $100,000\n");
 
    }
  return 0;
}


  
  int main()
{
    char input[MAXINPUT] = "";
    int length,i; 
    int temp = 1;
    while(1){
    temp = 1;
    scanf ("%s", input);
    length = strlen (input);
    for (i=0;i<length; i++){
        if (!isdigit(input[i]))
        {
            printf ("Entered input is not a number\n");
            temp = 0;
            break;
        }
        
    }
    if (temp == 1){
        double x = atof(input);
        LuxuryTax(x);
    }
}
}` Should solve the issue, although the code is a bit sloppy.
